name:face-recognition
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.35.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=26.4.0
  - readline=8.2
  - setuptools=79.0.0
  - six=1.17.0
  - sqlite=3.49.1
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025b
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cmake==4.0.0
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.57.0
      - graphviz==0.8.4
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lit==18.1.8
      - markupsafe==3.0.2
      - matplotlib==3.5.1
      - mpmath==1.3.0
      - mxnet==1.9.1
      - networkx==3.4.2
      - numpy==1.23.5
      - pillow==11.2.1
      - pyparsing==3.2.3
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.67.1
      - triton==2.0.0
      - urllib3==2.4.0
